# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  containers:
  - container: nodejs
    image: node:8.15-jessie
  - container: ubuntu
    image: lenisha/ubuntu16-docker:latest

trigger: 
  branches:
    include:
    - master
pr:
 autoCancel: true
 branches:
  include: 
   - azure-pipelines
   - master

jobs:
- job: RunNodeBuild
  container: nodejs
  pool:
    name: 'ubuntu18' # 'ubuntu18'

  steps:
    - template: node-steps.yml       

    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Build.SourcesDirectory)
        Contents: |
         deployment/*.yaml
        targetFolder: $(Build.ArtifactStagingDirectory)
        
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: drop

- job: RunDockerPublish
  container: ubuntu
  dependsOn: RunNodeBuild
  condition: and( succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  pool:
    name: 'ubuntu18'    #vmImage: 'Ubuntu 16.04'

  steps:
    - template: docker-steps.yml